export const alertConstants ={
    SUCCESS:"SUCCESS",
    ERROR:"ERROR",
    CLEAR:"CLEAR"
}

export const userConstants ={
    STUDENT_REGISTER_REQUEST: 'STUDENT_REGISTER_REQUEST',
    STUDENT_REGISTER_SUCCESS: 'STUDENT_REGISTER_SUCCESS',
    STUDENT_REGISTER_FAILURE: 'STUDENT_REGISTER_FAILURE',

    STUDENT_LOGIN_REQUEST: 'STUDENT_LOGIN_REQUEST',
    STUDENT_LOGIN_SUCCESS: 'STUDENT_LOGIN_SUCCESS',
    STUDENT_LOGIN_FAILURE: 'STUDENT_LOGIN_FAILURE',

    STUDENT_LOGOUT: 'STUDENT_LOGOUT',

    GET_DATA_REQUEST:'GET_DATA_REQUEST',
    GET_DATA_SUCCESS:'GET_DATA_SUCCESS',
    GET_DATA_FAILURE:'GET_DATA_FAILURE',
}

export const jobConstants ={
    JOB_POST_REQUEST:"JOB_POST_REQUEST",
    JOB_POST_SUCCESS:"JOB_POST_SUCCESS",
    JOB_POST_FAILURE:"JOB_POST_FAILURE"
}
